# Generated by Django 4.1.3 on 2022-11-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
