# Generated by Django 4.1.3 on 2022-11-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='fans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
